---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  message = FALSE
)
```
# watershedtools
The goal of `watershedtools` is to delineate watersheds using packages like nhdplusTools and others. Most methods will work best for the continental U.S.


## Installation

You can install watershedtools from github using devtools:

```{r gh-installation, eval = FALSE}
devtools::install_github("tylerbhampton/watershedtools")
```

## Test Watershed Delineation

```{r message=FALSE, warning=FALSE}
watershedtools::loadpackages(packages = c("watershedtools","ggplot2","sf","leaflet"))

# Point for Harlan County Lake on the Republican River, Nebraska USA
p=c(-99.189990,40.071521)

wsshape=NHDWBDws(method = "point",point = p,
         WBDstagepath = "B:/MASTERDATA/data_Hydrology/hydrology_shapefiles/USA_WBD_WatershedBoundaryDataset")


leaflet(data = wsshape) %>% leaflet::addPolygons() %>% leaflet::addProviderTiles("Esri.WorldImagery")
```

